name: CI-CD Pipeline

on:
  pull_request:
    types: [opened, closed, synchronize]
    branches: [main]

jobs:
  build-test:
    runs-on: self-hosted   # <-- this will run on the EC2 runner spun up by Terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python3 pip install -r app/requirements.txt
          python3 pip install pylint

      - name: Run Lint
        run: |
          pylint app/app.py
      - name: Run App
        run: |
          nohup python3 app.py > app.log 2>&1 &

      - name: Run Tests
        run: |
          python -m unittest discover tests
